config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]

  get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorites.includes(:favorites).where(created_at: from...to).size <=>
        a.favorites.includes(:favorites).where(created_at: from...to).size
      }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @new_book = Book.new
    @book_comment = BookComment.new
    @user = User.find(current_user.id)
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create #送られてきたform_forのパラメータを保存させる

      #form_forで送られてきたcontentを含む全てのメッセージの情報の:messageと:room_idのキーがちゃんと入っているか?
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?

      #メッセージを保存するためにMessage.createとし、Messagesテーブルにuser_id、:content、room_idのパラメーターとして送られてきた値を許可
      #現在ログインしているユーザーなので、そのuser_idの情報をmerge
      @message = Message.create(params.require(:message).permit(:user_id, :message, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @user = User.find(params[:id])
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def correct_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
	     <th>name</th>
	     <th><%= user.name %></th>
    </tr>
    <tr>
	     <th>introduction</th>
	     <th><%= user.introduction %></th>
    </tr>
    <tr>
	     <th>follows</th>
	     <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
    </tr>
    <tr>
	     <th>followers</th>
	     <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
    </tr>
    <tr><% if user.id == current_user.id %></tr>
    <% end %>
  </tbody>
</table>
<% if user == current_user %>
  <div class="row">
    <%= link_to " ", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
<% end %>
<table>
  <th>
    <% if user != current_user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    <% end %>
  </th>
  <th>
    <% if (current_user.following? @user) && (@user.following? current_user)  %>
      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" >chatを始める</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: @user.id %>
          <% end %>
            <%= f.submit "chatを始める" %>
        <% end %>
      <% end %>
    <% end %>
  </th>
</table>
<h2 class="mt-3">New book</h2>
<%= form_for(Book.new) do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <div class="error_explanation">
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
  		<%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
  		<%= link_to "Show", book_path %> |
  		<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div class="error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
           <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', books: @books, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image1.jpg"), user_path(book.user) %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              <td id="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite-btn", book: book %>
						  </td>
						  <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:success] %>
  <div class="flash">
    <%= flash[:success] %>
  </div>
<% end %>

<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', books: @books, user: @user, user: @book.user %>
    </div>
    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no_image1.jpg") %><br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td><%= @book.body %></td>
            <td id="favorite_btn_<%= @book.id %>">
              <%= render 'favorites/favorite-btn', book: @book %>
						</td>
　　　　　　<td>コメント数：<%= @book.book_comments.count %></td>
            <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id) , method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table>
        <tbody id="book_comment">
          <%= render 'book_comments/book_comment', book: @book %>
        </tbody>
      </table>
      <%= form_with model:[@book,@book_comment], remote: true do |f| %>
        <%= f.text_area :comment, rows:'5' %><br>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<h1><%= @user.name %> さんとのチャット</h1>

<div class="message" style="width: 500px;">
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <% if m.user_id == current_user.id %>
      <p style="text-align: right;"><%= m.message %></p>
    <% else %>
      <p style="text-align: left;"><%= m.message %></p>
    <% end %>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>
</div>
<%= form_for @message do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id, :value => @room.id %>
<% end %>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <% if @user.errors.any? %>
        <div class="error_explanation">
          <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class:"form-control name" %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class:"form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', books: @books, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |f| %>
          <tr>
            <td>
              <%= attachment_image_tag f, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image1.jpg" %>
            </td>
            <td>
              <%= f.name %>
            </td>
            <td>フォロー数: <%= f.followings.count %></td>
            <td>フォロワー数: <%= f.followers.count %></td>
            <td>
              <% if f != current_user %>
                <% if current_user.following?(f) %>
                  <%= link_to "フォロー外す", user_relationships_path(f.id), method: :delete %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(f.id), method: :post %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to "Show", user_path(f.id) %>
            </td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:success] %>
  <div class="flash">
    <%= flash[:success] %>
  </div>
<% end %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', books: @books, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |f| %>
          <tr>
            <td>
              <%= link_to attachment_image_tag(f.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image1.jpg"), user_path(f.user.id) %>
            </td>
            <td>
              <%= link_to f.title, book_path(f.id) %>
            </td>
            <td>
              <%= f.body %>
            </td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>